services:
  - type: web
    name: music-player-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret